// Dev-only: regenerate the footer ASCII art. Never imported at runtime.
// Usage: pnpm gen:ascii [TEXT] [OUT_PATH]
import figlet from "figlet";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const text = process.argv[2] ?? "M4SS1CK";
const out = process.argv[3] ?? "src/assets/ascii/m4ss1ck.ts";

// "ANSI Shadow" gives bold block letters. If the rendered banner shows missing
// glyphs (tofu) because the web font lacks box-drawing chars, regenerate with an
// ASCII-only font, e.g.:  pnpm gen:ascii M4SS1CK src/assets/ascii/m4ss1ck.ts -- Big
const font = (process.argv[4] as figlet.Fonts) ?? "ANSI Shadow";

const art = figlet.textSync(text, { font });

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
    out,
    `// Generated by scripts/generate-ascii.ts — do not edit by hand.\n` +
        `export const m4ss1ckArt = ${JSON.stringify(art)};\n`,
);

console.log(art);
console.log(`\nWrote ${out}`);
